---
# tasks file for tomcat9
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install the latest version of java
  yum:
    name: java-11-openjdk
    state: latest

- name: Create tomcat group
  group:
    name: tomcat
    state: present


- name: create a tomcat user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat


- name: Create a tomcat directory and Grant permission
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'
    owner: tomcat
    group: tomcat
    recurse: yes



- name: Download tomcat
  get_url:
    url: "{{ tomcat_link }}"
    dest: /opt/tomcat


- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "/opt/tomcat/{{ tomcat_pkg }}"
    dest: /opt/tomcat/
    remote_src: no
    mode: 0755
    owner: tomcat
    group: tomcat


- name: copy tomcat-users.xml to tomcat_home/conf
  copy:
    src: "{{ users_xml }}"
    dest: "{{ conf_link }}"
    remote_src: no
    owner: tomcat
    group: tomcat
    mode: 0755


- name: copy context.xml to tomcat_home/meta-inf
  copy:
    src: "{{ context_xml }}"
    dest: "{{ meta_inf }}"
    remote_src: no
    owner: tomcat
    group: tomcat
    mode: 0755


- name: Firewalld to open the required port
  firewalld:
    port: "{{ port }}/{{ proto }}"
    permanent: yes
    immediate: yes
    state: enabled
    zone: "{{ zone }}"



- name: copy tomcat service to systemd
  copy:
    src: tomcat/files/tomcat.service
    dest: /etc/systemd/system/
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: reload tomcat service
  systemd:
    daemon_reload: yes

- name: Start tomcat service
  service:
    name: tomcat.service
    state: started

- name: Enable tomcat service
  service:
    name: tomcat.service
    enabled: yes
  notify:
    - Restart tomcat service


- name: download jenkins
  get_url:
    url: "{{ jenkins_pkg }}"
    dest: "{{ webapps_link }}"
    owner: root
    group: root
    mode: 0755


